### PR TITLE
test-kitchen

### PR DESCRIPTION
**Pull request by sdarwin**
Hi,

When running Test Kitchen for Ubuntu 18 and Centos 7, there were a few errors. It wouldn't build.

github.alaska.edu:oit-cookbooks was commented out, since I don't have access to it.  You can most likely reproduce all the same errors which I encountered by temporarily removing the oit-cookbooks.

Summary of fixes:

- Support the newer apache2 cookbook version 7.   
"apache_service" -> "apache2"
"apache_module" -> "apache2_module"
						
- conf.d -> conf-available, 
It seems that in a recent version the http_platform cookbook changed "def config_relative_directory" from conf.d to conf-available.
Therefore, django_platform also had to make the corresponding change. 
At least, the two cookbooks should match each other.
Possible future reorganization ? : remove config_absolute_directory entirely and standardize on conf-available.

- Corrected path for python on Redhat: python36 -> python3.

- make sure git is installed

- path to socket must be set for Redhat. /var/run/wsgi , because apache doesn't have permissions to the /var/run/httpd/ folder.

- disable selinux on redhat. The user can modify node['selinux']['state'] to adjust the variable. A more sophisticated solution might be to include a specific apache/django selinux policy in the cookbook.

### CODE REVIEW

**Review by calsev — COMMENTED** [review]
Wow, two PRs in one week! I have had a semi-stale branch going for a while that I just happened to revisit the same day as your PR. It delegates much of the install logic to  *_install cookbooks. This has the advantage that more platforms will be able to support the LTS version of Django (2.2). I my first inclination is to rebase that branch on yours and merge the changes as one revision.

**Comment by sdarwin** [comment]
Hi Caleb,
Ok.  Sounds like a good plan.

**Comment by sdarwin** [comment]
Hi Caleb,
It seems like there is great value in having a "Django" cookbook.  This could be used by anyone who leverages Chef and Django. I believe that >90% of Django users will prefer "package" installs of python, openssl, sqlite. Those packages are standard, well supported, and fast to install. On the other hand, installing from source is really slow, and might involve some debugging.

What do you think - could the cookbook install "packages" by default, and only install from source if the user selects it?

An example of such functionality in https://github.com/sous-chefs/nagios -

```
node['nagios']['server']['install_method'] - whether to install from package or source. Default chosen by platform based on known packages available for Nagios: debian/ubuntu 'package', redhat/centos/scientific: source
```

**Comment by calsev** [comment]
Sam:

I agree the source install is a hard pill to swallow. I do prefer to stick with packages when possible to avail of backports for security.

The forcing factor for the source build was supporting LTS Django on CentOS 7, which spiraled into also building OpenSSL and SQLite. It seems the Django way of doing things and the RHEL way are fairly incompatible.

I see two problems with source installs: build times and patch support.

I considered a PPA+package approach to save long build times for clients. However, that mitigates only the build time.

The split method is a good idea! Packaged dependencies so far work great for Django on Debian-based systems. I would definitely make package install the default on those distros. I suppose package install could be default everywhere and the ReadMe could point to using source install for using new Django on old distros.

**Comment by calsev** [comment]
I can revert the removal of package and venv code and add a thin layer of switch logic to choose between the approaches. I was considering reverting to venv for source install anyway because that improves support for having Django's Python environment active when running custom batch scripts.

**Review by calsev — CHANGES_REQUESTED** [review]
Revert package+venv code and provide switch for install method. See [nagios cookbook](https://github.com/sous-chefs/nagios).

**Review by calsev — APPROVED** [review]

**Pull request merged**
